### ISSUE TITLE
Error tying to load repl

### ISSUE THREAD

**Issue by kidpollo** [arachne-framework/demo#2]
running `lein repl` does not work for me.

Is there something obvious I'm missing?

```
Starting nREPL server...
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -XX:-OmitStackTraceInFastThrow -Dclojure.compile.path=/Users/pacov/code/demo/target/classes -Ddemo.version=0.1.0-SNAPSHOT -Dclojure.debug=false -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -classpath "/Users/pacov/code/demo/test:/Users/pacov/code/demo/src:/Users/pacov/code/demo/dev-resources:/Users/pacov/code/demo/resources:/Users/pacov/code/demo/target/classes:/Users/pacov/.m2/repository/com/datomic/datomic-lucene-core/3.3.0/datomic-lucene-core-3.3.0.jar:/Users/pacov/.m2/repository/io/aviso/pretty/0.1.14/pretty-0.1.14.jar:/Users/pacov/.m2/repository/org/apache/activemq/artemis-commons/1.4.0/artemis-commons-1.4.0.jar:/Users/pacov/.m2/repository/org/apache/tomcat/tomcat-juli/7.0.27/tomcat-juli-7.0.27.jar:/Users/pacov/.m2/repository/org/flatland/classlojure/0.7.0/classlojure-0.7.0.jar:/Users/pacov/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/pacov/.m2/repository/lein-as-resource/lein-as-resource/2.5.0/lein-as-resource-2.5.0.jar:/Users/pacov/.m2/repository/org/tcrawley/dynapath/0.2.3/dynapath-0.2.3.jar:/Users/pacov/.m2/repository/mvxcvi/whidbey/0.4.2/whidbey-0.4.2.jar:/Users/pacov/.m2/repository/com/h2database/h2/1.3.171/h2-1.3.171.jar:/Users/pacov/.m2/repository/jonase/eastwood/0.2.1/eastwood-0.2.1.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/http2/http2-server/9.3.8.v20160314/http2-server-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/im/chit/hara.class.inheritance/2.1.8/hara.class.inheritance-2.1.8.jar:/Users/pacov/.m2/repository/tigris/tigris/0.1.1/tigris-0.1.1.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-io/9.3.8.v20160314/jetty-io-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/websocket/websocket-server/9.3.8.v20160314/websocket-server-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar:/Users/pacov/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar:/Users/pacov/.m2/repository/transduce/transduce/0.1.0/transduce-0.1.0.jar:/Users/pacov/.m2/repository/im/chit/hara.reflect/2.1.8/hara.reflect-2.1.8.jar:/Users/pacov/.m2/repository/org/clojure/core.memoize/0.5.8/core.memoize-0.5.8.jar:/Users/pacov/.m2/repository/crypto-random/crypto-random/1.2.0/crypto-random-1.2.0.jar:/Users/pacov/.m2/repository/im/chit/hara.class/2.1.8/hara.class-2.1.8.jar:/Users/pacov/.m2/repository/com/cognitect/transit-clj/0.8.285/transit-clj-0.8.285.jar:/Users/pacov/.m2/repository/org/slf4j/jul-to-slf4j/1.7.12/jul-to-slf4j-1.7.12.jar:/Users/pacov/.m2/repository/ring/ring-codec/1.0.0/ring-codec-1.0.0.jar:/Users/pacov/.m2/repository/org/clojure/core.match/0.3.0-alpha4/core.match-0.3.0-alpha4.jar:/Users/pacov/.m2/repository/fipp/fipp/0.4.3/fipp-0.4.3.jar:/Users/pacov/.m2/repository/org/arachne-framework/arachne-pedestal/0.1.0-master-0024-0d8fb38/arachne-pedestal-0.1.0-master-0024-0d8fb38.jar:/Users/pacov/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.5.3/jackson-dataformat-smile-2.5.3.jar:/Users/pacov/.m2/repository/org/codehaus/janino/commons-compiler/2.6.1/commons-compiler-2.6.1.jar:/Users/pacov/.m2/repository/clj-time/clj-time/0.9.0/clj-time-0.9.0.jar:/Users/pacov/.m2/repository/org/clojure/tools.analyzer/0.6.7/tools.analyzer-0.6.7.jar:/Users/pacov/.m2/repository/org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar:/Users/pacov/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.12/log4j-over-slf4j-1.7.12.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.3.8.v20160314/websocket-client-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/clojure/tools.reader/1.0.0-alpha1/tools.reader-1.0.0-alpha1.jar:/Users/pacov/.m2/repository/slamhound/slamhound/1.5.5/slamhound-1.5.5.jar:/Users/pacov/.m2/repository/org/clojure/tools.analyzer.jvm/0.6.9/tools.analyzer.jvm-0.6.9.jar:/Users/pacov/.m2/repository/cider/cider-nrepl/0.8.2/cider-nrepl-0.8.2.jar:/Users/pacov/.m2/repository/aysylu/loom/0.5.4/loom-0.5.4.jar:/Users/pacov/.m2/repository/org/clojure/core.async/0.2.374/core.async-0.2.374.jar:/Users/pacov/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-server/9.3.8.v20160314/jetty-server-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/http2/http2-common/9.3.8.v20160314/http2-common-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/clojars/brenton/google-diff-match-patch/0.1/google-diff-match-patch-0.1.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/websocket/websocket-servlet/9.3.8.v20160314/websocket-servlet-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/im/chit/hara.class.checks/2.1.8/hara.class.checks-2.1.8.jar:/Users/pacov/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar:/Users/pacov/.m2/repository/org/clojure/data.priority-map/0.0.5/data.priority-map-0.0.5.jar:/Users/pacov/.m2/repository/org/apache/johnzon/johnzon-core/0.9.4/johnzon-core-0.9.4.jar:/Users/pacov/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar:/Users/pacov/.m2/repository/ring/ring-core/1.4.0/ring-core-1.4.0.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.3.8.v20160314/http2-hpack-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-http/9.3.8.v20160314/jetty-http-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/pacov/.m2/repository/org/clojure/java.classpath/0.2.0/java.classpath-0.2.0.jar:/Users/pacov/.m2/repository/crypto-equality/crypto-equality/1.0.0/crypto-equality-1.0.0.jar:/Users/pacov/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/pacov/.m2/repository/io/pedestal/pedestal.service/0.5.0/pedestal.service-0.5.0.jar:/Users/pacov/.m2/repository/alembic/alembic/0.3.2/alembic-0.3.2.jar:/Users/pacov/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.12/jcl-over-slf4j-1.7.12.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-util/9.3.8.v20160314/jetty-util-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/Users/pacov/.m2/repository/com/datomic/datomic-free/0.9.5407/datomic-free-0.9.5407.jar:/Users/pacov/.m2/repository/com/stuartsierra/dependency/0.2.0/dependency-0.2.0.jar:/Users/pacov/.m2/repository/io/pedestal/pedestal.jetty/0.5.0/pedestal.jetty-0.5.0.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.3.8.v20160314/websocket-api-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/im/chit/hara.common.error/2.1.8/hara.common.error-2.1.8.jar:/Users/pacov/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar:/Users/pacov/.m2/repository/org/clojure/tools.logging/0.3.1/tools.logging-0.3.1.jar:/Users/pacov/.m2/repository/org/clojure/core.incubator/0.1.3/core.incubator-0.1.3.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.8.v20160314/jetty-servlet-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/fressian/fressian/0.6.5/fressian-0.6.5.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-security/9.3.8.v20160314/jetty-security-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/apache/geronimo/specs/geronimo-json_1.0_spec/1.0-alpha-1/geronimo-json_1.0_spec-1.0-alpha-1.jar:/Users/pacov/.m2/repository/mvxcvi/puget/0.6.6/puget-0.6.6.jar:/Users/pacov/.m2/repository/com/stuartsierra/component/0.3.1/component-0.3.1.jar:/Users/pacov/.m2/repository/im/chit/hara.common.primitives/2.1.8/hara.common.primitives-2.1.8.jar:/Users/pacov/.m2/repository/org/clojure/data.finger-tree/0.0.2/data.finger-tree-0.0.2.jar:/Users/pacov/.m2/repository/org/apache/activemq/artemis-core-client/1.4.0/artemis-core-client-1.4.0.jar:/Users/pacov/.m2/repository/org/arachne-framework/arachne-core/0.1.0-master-0057-ad6d720/arachne-core-0.1.0-master-0057-ad6d720.jar:/Users/pacov/.m2/repository/venantius/ultra/0.1.9/ultra-0.1.9.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/jetty-alpn-server/9.3.8.v20160314/jetty-alpn-server-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/org/ow2/asm/asm-all/4.2/asm-all-4.2.jar:/Users/pacov/.m2/repository/im/chit/hara.common.checks/2.1.8/hara.common.checks-2.1.8.jar:/Users/pacov/.m2/repository/cljs-tooling/cljs-tooling/0.1.3/cljs-tooling-0.1.3.jar:/Users/pacov/.m2/repository/org/clojure/clojure/1.9.0-alpha14/clojure-1.9.0-alpha14.jar:/Users/pacov/.m2/repository/org/clojure/tools.cli/0.2.2/tools.cli-0.2.2.jar:/Users/pacov/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar:/Users/pacov/.m2/repository/org/clojure/core.cache/0.6.4/core.cache-0.6.4.jar:/Users/pacov/.m2/repository/org/arachne-framework/arachne-http/0.1.0-master-0034-50eb10d/arachne-http-0.1.0-master-0034-50eb10d.jar:/Users/pacov/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/pacov/.m2/repository/org/clojure/tools.trace/0.7.8/tools.trace-0.7.8.jar:/Users/pacov/.m2/repository/org/clojure/tools.namespace/0.2.5/tools.namespace-0.2.5.jar:/Users/pacov/.m2/repository/compliment/compliment/0.2.0/compliment-0.2.0.jar:/Users/pacov/.m2/repository/im/chit/hara.common.hash/2.1.8/hara.common.hash-2.1.8.jar:/Users/pacov/.m2/repository/io/netty/netty-all/4.0.39.Final/netty-all-4.0.39.Final.jar:/Users/pacov/.m2/repository/com/cognitect/transit-java/0.8.311/transit-java-0.8.311.jar:/Users/pacov/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/Users/pacov/.m2/repository/cheshire/cheshire/5.5.0/cheshire-5.5.0.jar:/Users/pacov/.m2/repository/im/chit/vinyasa.inject/0.3.0/vinyasa.inject-0.3.0.jar:/Users/pacov/.m2/repository/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar:/Users/pacov/.m2/repository/org/msgpack/msgpack/0.6.10/msgpack-0.6.10.jar:/Users/pacov/.m2/repository/org/codehaus/janino/commons-compiler-jdk/2.6.1/commons-compiler-jdk-2.6.1.jar:/Users/pacov/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.3.2/jackson-core-2.3.2.jar:/Users/pacov/.m2/repository/joda-time/joda-time/2.6/joda-time-2.6.jar:/Users/pacov/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar:/Users/pacov/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.3.8.v20160314/websocket-common-9.3.8.v20160314.jar:/Users/pacov/.m2/repository/im/chit/hara.data.map/2.1.8/hara.data.map-2.1.8.jar:/Users/pacov/.m2/repository/org/eclipse/jetty/alpn/alpn-api/1.1.2.v20150522/alpn-api-1.1.2.v20150522.jar:/Users/pacov/.m2/repository/org/apache/tomcat/tomcat-jdbc/7.0.27/tomcat-jdbc-7.0.27.jar:/Users/pacov/.m2/repository/im/chit/hara.namespace.import/2.1.8/hara.namespace.import-2.1.8.jar:/Users/pacov/.m2/repository/commons-codec/commons-codec/1.5/commons-codec-1.5.jar:/Users/pacov/.m2/repository/im/chit/hara.common/2.1.8/hara.common-2.1.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain clojure.main -i /private/var/folders/31/ccrpn0qs4qj_zs93mdp4scpc0000gn/T/form-init4057396369787505808.clj
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: hara.common.checks, being replaced by: #'hara.common.checks/boolean?
WARNING: double? already refers to: #'clojure.core/double? in namespace: hara.common.checks, being replaced by: #'hara.common.checks/double?
WARNING: bigdec? already refers to: #'clojure.core/bigdec? in namespace: hara.common.checks, being replaced by: #'hara.common.checks/bigdec?
WARNING: uuid? already refers to: #'clojure.core/uuid? in namespace: hara.common.checks, being replaced by: #'hara.common.checks/uuid?
WARNING: uri? already refers to: #'clojure.core/uri? in namespace: hara.common.checks, being replaced by: #'hara.common.checks/uri?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: hara.common.checks, being replaced by: #'hara.common.checks/bytes?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: hara.common.primitives, being replaced by: #'hara.common.checks/bytes?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: hara.common, being replaced by: #'hara.common/boolean?
WARNING: uri? already refers to: #'clojure.core/uri? in namespace: hara.common, being replaced by: #'hara.common/uri?
WARNING: double? already refers to: #'clojure.core/double? in namespace: hara.common, being replaced by: #'hara.common/double?
WARNING: bigdec? already refers to: #'clojure.core/bigdec? in namespace: hara.common, being replaced by: #'hara.common/bigdec?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: hara.common, being replaced by: #'hara.common/bytes?
WARNING: uuid? already refers to: #'clojure.core/uuid? in namespace: hara.common, being replaced by: #'hara.common/uuid?
Exception in thread "main" clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec:
In: [1] val: ((require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all])) fails at: [:args] predicate: (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses),  Extra input
:clojure.spec/args  (hara.reflect.pretty.classes (require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all]))
 #:clojure.spec{:problems [{:path [:args], :reason "Extra input", :pred (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses), :val ((require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all])), :via [], :in [1]}], :args (hara.reflect.pretty.classes (require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all]))}, compiling:(hara/reflect/pretty/classes.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7442)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7846.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5889)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at hara.reflect.element.multi$eval3637$loading__7732__auto____3638.invoke(multi.clj:1)
	at hara.reflect.element.multi$eval3637.invokeStatic(multi.clj:1)
	at hara.reflect.element.multi$eval3637.invoke(multi.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7846.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5893)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at hara.reflect.core.apply$eval3380$loading__7732__auto____3381.invoke(apply.clj:1)
	at hara.reflect.core.apply$eval3380.invokeStatic(apply.clj:1)
	at hara.reflect.core.apply$eval3380.invoke(apply.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7846.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5893)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at hara.reflect$eval3374$loading__7732__auto____3375.invoke(reflect.clj:1)
	at hara.reflect$eval3374.invokeStatic(reflect.clj:1)
	at hara.reflect$eval3374.invoke(reflect.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7846.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5889)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at ultra.reflect$eval3285$loading__7732__auto____3286.invoke(reflect.clj:1)
	at ultra.reflect$eval3285.invokeStatic(reflect.clj:1)
	at ultra.reflect$eval3285.invoke(reflect.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7846.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5889)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at ultra.hardcore$eval1533$loading__7732__auto____1534.invoke(hardcore.clj:1)
	at ultra.hardcore$eval1533.invokeStatic(hardcore.clj:1)
	at ultra.hardcore$eval1533.invoke(hardcore.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7846.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5889)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval1527.invokeStatic(form-init4057396369787505808.clj:1)
	at user$eval1527.invoke(form-init4057396369787505808.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6978)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec:
In: [1] val: ((require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all])) fails at: [:args] predicate: (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses),  Extra input
:clojure.spec/args  (hara.reflect.pretty.classes (require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all]))
 {:clojure.spec/problems [{:path [:args], :reason "Extra input", :pred (cat :docstring (? string?) :attr-map (? map?) :clauses :clojure.core.specs/ns-clauses), :val ((require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all])), :via [], :in [1]}], :clojure.spec/args (hara.reflect.pretty.classes (require [hara.reflect.common :refer :all] [hara.reflect.pretty.primitives :refer :all]))}
	at clojure.core$ex_info.invokeStatic(core.clj:4725)
	at clojure.spec$macroexpand_check.invokeStatic(spec.clj:681)
	at clojure.spec$macroexpand_check.invoke(spec.clj:670)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6816)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6888)
	at clojure.lang.Compiler.eval(Compiler.java:6962)
	at clojure.lang.Compiler.load(Compiler.java:7430)
	... 184 more
No nREPL ack received

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

**Comment by kidpollo** [comment]
It seems to work if its loaded as a normal jvm process

**Comment by levand** [comment]
Per the error message, it looks like the Hara library has a malformed NS declaration. Clojure 1.9 is much stricter about what can appear in `ns` forms than previous versions of Clojure, now that there is actually a spec for it.

This happens when running via leiningen, but not via a normal JVM process, because Arachne itself has no dependency on Hara. Hara must be getting pulled in via a lein plugin or something else in your global lein config.

If you want to use a leiningen-based REPL, you should remove whatever is causing Hara to be included from your global lein config until Hara is updated to be 1.9-compatible. 

Or you can just continue to use "run in normal JVM process"

**Comment by kidpollo** [comment]
Thanks!
